services:
  # Registrar repositorios como servicios explícitamente
  App\Repository\RegionRepository:
    factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
    arguments:
      - 'App\Entity\Region'
    tags: ['doctrine.repository_service']
    public: true

