services:
  # Registrar repositorios como servicios explícitamente
  App\Repository\HolaRepository:
    factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
    arguments:
      - 'App\Entity\Hola'
    tags: ['doctrine.repository_service']
    public: true
    autowire: true  # Activar autowire para que Symfony gestione las dependencias automáticamente

